### ISSUE TITLE
Is there a way to get current status of a channel?

### ISSUE THREAD

**Issue by ribaptista** [peake100/rogerRabbit-go#55]
I'm using `rogerRabbit-go` on a project and I'm totally relying on it to retry to connect on connection disruptions.

But now I need to write a healthcheck route for my app, and it would be nice if I could retrieve the current status of a channel (is it healthy? Is it attempting to reconnect?).

Is that possible?

Thanks!

**Comment by peake100** [comment]
Hello!

Glad you found this useful! Take a look at the docs for the following two methods and let me know if it serves your needs. You could have a routine listening to both event channels and storing the last update for your health check:

- [NotifyDisconnect](https://pkg.go.dev/github.com/peake100/rogerRabbit-go@v0.4.19/pkg/amqp#Channel.NotifyDisconnect)
- [NotifyDial](https://pkg.go.dev/github.com/peake100/rogerRabbit-go@v0.4.19/pkg/amqp#Channel.NotifyDial)
- [NotifyClose](https://pkg.go.dev/github.com/peake100/rogerRabbit-go@v0.4.19/pkg/amqp#Channel.NotifyClose)

You could do something like this:

```go
	disconnectEvents := make(chan error, 0)
	dialEvents := make(chan error, 0)
	closeEvents := make(chan *amqp.Error, 0)
	
	err := channel.NotifyDisconnect(disconnectEvents)
	if err != nil {
		return err
	}
	
	err = channel.NotifyDial(dialEvents)
	if err != nil {
		return err
	}
	
	channel.NotifyClose(closeEvents)
	if err != nil {
		return err
	}
	
	isDisconnected := true
	go func() {
		var err error
		for {
			select {
			case err = <- disconnectEvents:
				isDisconnected = true
			case err = <- dialEvents:
				if err != nil {
					isDisconnected = true
				} else {
					isDisconnected = false
				}
			case <- closeEvents:
				isDisconnected = true
				return
			}
		}
	}()
```

You would need to add a mutex or some other way to sync update the state, but this should give you an idea. Let me know if that solves your issue!

**Comment by peake100** [comment]
Another option is to write a [middleware](https://peake100.github.io/rogerRabbit-go/amqp.html#channel-middleware) that handles this. 

All the middleware definitions can be found [here](https://pkg.go.dev/github.com/peake100/rogerRabbit-go@v0.4.19/pkg/amqp/amqpmiddleware)

[The default middleware](https://pkg.go.dev/github.com/peake100/rogerRabbit-go@v0.4.19/pkg/amqp/defaultmiddlewares) can serve as examples of middleware that provide complex behavior based on multiple events / method handlers.

You could write a middleware for disconnection, dial, and close events that updates or can be inspected by your health-checking route.

**Comment by ribaptista** [comment]
Wow, thank you so much for being so helpful! I'm surely gonna try those ideas today!

**Comment by peake100** [comment]
No problem! I'm going to close this issue for now, but feel free to drop by or open a new one if you run into issues. Thanks!
