### ISSUE TITLE
Build fail; error: `undefined: pears.BatchErrors`, `undefined: pears.BatchMatchFirst`

### ISSUE THREAD

**Issue by sogko** [peake100/rogerRabbit-go#56]
```
# github.com/peake100/rogerRabbit-go/pkg/roger/rconsumer
../../../peake100/rogerRabbit-go/pkg/roger/rconsumer/requiredMiddleware.go:59:16: undefined: pears.BatchErrors
../../../peake100/rogerRabbit-go/pkg/roger/rconsumer/requiredMiddleware.go:60:22: undefined: pears.BatchMatchFirst
```

`rconsumer` references `github.com/peake100/pears-go/pkg/pears` package; if I have to guess, it seems like it some changes were out of sync/not committed to the `pears` package?

**Comment by peake100** [comment]
Hello!

I don't believe I have done any work on either of these packages in quite some time, and either way the go.mod file should make certain that the correct version of `pears` is being used. Can you give me more context on what you were doing when you got this error?

Thanks!

**Comment by peake100** [comment]
Closing as inactive
