### ISSUE TITLE
Feature: Expand Middleware to all Methods

### ISSUE THREAD

**Issue by peake100** [peake100/rogerRabbit-go#6]
Currently, only channel methods that are required for the default middleware support middleware registration.

Middleware registration should be enabled on all methods.

**Comment by lkamak** [comment]
Hey! I'm brand new to open source contributing and this would be my first contribution. Do you think I could have a go at this issue? Thanks!

**Comment by peake100** [comment]
Hey! I'm sorry I am just seeing this.

Go for it! I have not yet really promoted this lib and am just sort of using it for my own stuff, but once it's a little more battle-tested I do plan to promote it!

Thanks for your interest in the lib let me know if you have any questions as you dig into the code.
